openapi: 3.0.0

info:
  title: Survey API
  description: API for Surveys
  version: 1.0.0

servers:
  - url: https://192.168.1.206:45455

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RefreshToken:
      type: object
      properties:
        rToken:
          type: string
        expires:
          type: string
        createdBy:
          type: integer
        revoked:
          type: boolean

    LoginRequestBody:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        pid:
          type: integer
        userName:
          type: string
        hashedPwd:
          type: string
        refreshToken:
          $ref: "#/components/schemas/RefreshToken"
        roleID:
          type: string
        customField01:
          type: string
        customField02:
          type: string
        customField03:
          type: string

    FastLoginRequestBody:
      type: object
      properties:
        token:
          type: string

    LogoutResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: integer
        message:
          type: string
        error:
          type: string

    OnlyPidParameter:
      type: object
      properties:
        pid:
          type: integer

    OpenapiUser:
      type: object
      properties:
        pid:
          type: integer
        UserName:
          type: string
        Password:
          type: string
        RoleID:
          type: string

    OpenapiSurveyDetail:
      type: object
      properties:
        sdid:
          type: integer
        seid:
          type: integer
        descr:
          type: string
        CustomField01:
          type: string
        CustomField02:
          type: string
        CustomField03:
          type: string

    OpenapiSurvey:
      type: object
      properties:
        seid:
          type: integer
        title:
          type: string
        descr:
          type: string
        customField01:
          type: string
        isOpen:
          type: string
        customField03:
          type: string
        surveyDetails:
          type: array
          items:
            $ref: "#/components/schemas/OpenapiSurveyDetail"

paths:
  /service/login:
    post:
      operationId: "login"
      description: "Performs a standard login"
      requestBody:
        description: "Username and password"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestBody"

      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          description: "Incorrect data"
          content:
            text/plain:
              schema:
                type: string

  /service/fastLogin:
    post:
      operationId: "fastLogin"
      description: "Login with refresh token"
      requestBody:
        description: "Refresh token"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FastLoginRequestBody"
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          description: "Incorrect data"
          content:
            application/json:
              schema:
                type: string

  /service/signUp:
    post:
      operationId: "signUp"
      description: "Sign up"
      requestBody:
        description: "Username, Password and RoleID"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenapiUser"
      responses:
        200:
          description: "Success."
          content:
            text/plain:
              schema:
                type: boolean
        400:
          description: "Couldn't sign up"
          content:
            text/plain:
              schema:
                type: boolean

  /service/logout:
    post:
      operationId: "logout"
      description: "Logout"
      requestBody:
        description: "pid"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OnlyPidParameter"
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LogoutResponse"

  /service/loadAllSurveysByUser:
    get:
      operationId: "loadAllSurveysByUser"
      description: "load all surveys by user"
      parameters:
        - in: query
          name: pid
          schema:
            type: integer
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OpenapiSurvey"

  /service/loadAllSurveysExceptUser:
    get:
      operationId: "loadAllSurveysExceptUser"
      description: "load all surveys except the ones of the current user"
      parameters:
        - in: query
          name: pid
          schema:
            type: integer
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OpenapiSurvey"

  /service/addSurveyEntity:
    post:
      operationId: "createSurvey"
      description: "Create survey"
      requestBody:
        description: "survey"
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/OpenapiSurvey"
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OpenapiSurvey"

  /service/getSurveyDetails:
    get:
      operationId: "getSurveyDetails"
      description: "Gets the specified survey's entries"
      parameters:
        - in: query
          name: seid
          schema:
            type: integer
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OpenapiSurveyDetail"

  /service/deleteSurvey:
    delete:
      operationId: "deleteSurvey"
      description: "Deletes a survey"
      parameters:
        - in: query
          name: seid
          schema:
            type: integer
      responses:
        200:
          description: "Success."
