openapi: 3.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RefreshToken:
      type: object
      properties:
        rToken:
          type: string
        expires:
          type: string
        createdBy:
          type: integer
        revoked:
          type: boolean

    LoginRequestBody:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        pid:
          type: integer
        userName:
          type: string
        hashedPwd:
          type: string
        refreshToken:
          $ref: "#/components/schemas/RefreshToken"
        roleID:
          type: string
        customField01:
          type: string
        customField02:
          type: string
        customField03:
          type: string

    FastLoginRequestBody:
      type: object
      properties:
        token:
          type: string

    User:
      type: object
      properties:
        pid:
          type: integer
        UserName:
          type: string
        Password:
          type: string
        RoleID:
          type: string

info:
  title: Survey API
  description: API for Surveys
  version: 1.0.0

servers:
  - url: https://192.168.1.206:45455

paths:
  /service/login:
    post:
      operationId: "login"
      description: "Performs a standard login"
      requestBody:
        description: "Username and password"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestBody"

      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          description: "Incorrect data"
          content:
            text/plain:
              schema:
                type: string

  /service/fastlogin:
    post:
      operationId: "fastLogin"
      description: "Login with refresh token"
      requestBody:
        description: "Refresh token"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FastLoginRequestBody"
      responses:
        200:
          description: "Success."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        400:
          description: "Incorrect data"
          content:
            text/plain:
              schema:
                type: string

  /service/signup:
    post:
      operationId: "signUp"
      description: "Sign up"
      requestBody:
        description: "Username, Password and RoleID"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: "Success."
          content:
            text/plain:
              schema:
                type: boolean
        400:
          description: "Couldn't sign up"
          content:
            text/plain:
              schema:
                type: boolean
